[package]
name = "ray_trace"
version = "0.1.0"
authors = ["jlingohr <johannlingohr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
